services:
    nginx:
        container_name: nginx
        image: nginx:1.25
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx-80.conf:/etc/nginx/nginx.conf
            - ./nginx/index.html:/etc/nginx/html/index.html
